### ISSUE TITLE
Purrlaroids should align left instead of center

### ISSUE THREAD

**Issue by madeleine-patience** [madeleine-patience/Considerate-Cat-Version-2-With-Next#25]
I think the cards should align left, not centered. Open to opinons.

![image](https://github.com/user-attachments/assets/4395a8a1-dd6a-45fe-a92c-4dcd3e55f5cd)

**Comment by ChaudaryHammad** [comment]
Hi @madeleine-patience , I’d like to contribute to issue #25.

**Comment by madeleine-patience** [comment]
@ChaudaryHammad Thanks so much for your interest in my project, we're not quite ready to accept PRs from the community yet. If you star the project we will let you know when its ready :) 

-Meow!

**Comment by ChaudaryHammad** [comment]
oh! it's oky.
