### ISSUE TITLE
Automate changelog

### ISSUE THREAD

**Issue by arthvadrr** [madeleine-patience/Considerate-Cat-Version-2-With-Next#59]
Use existing husky pre-commit hook to automate changes in the changelog.

**Comment by arthvadrr** [comment]
Still looking into this. I'm trying to make it as hands-off as possible, but also while using a safe non-destructive approach (and preferably one that doesn't create infinite commit loops 😅).

**Comment by madeleine-patience** [comment]
Take your time! Its no rush. Will be great when its ready!
